### ISSUE TITLE
Two Illegal String Offsets in acf-image-crop-v4.php

### ISSUE THREAD

**Issue by johncowleyhall** [andersthorborg/ACF-Image-Crop#26]
This plugin is fantastic, but I've noticed one thing: I get PHP warnings in the error log about illegal string offsets for 'retina_mode' and 'hide_cropped' in acf-image-crop-v4.php. Not a huge deal, to be sure, but I think changing lines 922 and 934 to do an isset() for the appropriate key in $options before setting $value fixes this.

Now, I'm not sure why my install is using v4.php instead of v5, but that's a bit beyond my current understanding. That being said, this whole issue may be moot. But I figured I'd let you know anyway.

Keep up the awesome work!

John

**Comment by andersthorborg** [comment]
Thanks for your feedback. Be aware that the version here on Github is outdated compared to the one that lives in the Wordpress Plugin Repository. So I'll recommend using that one instead.

**Comment by johncowleyhall** [comment]
You're welcome. I'm actually using the one from the Wordpress Plugin Repository, I just didn't want to sign up there in order to let you know about this. Regardless, thanks for listening, sir.

**Comment by andersthorborg** [comment]
I see. Is this happening in the newest version of the plugin? I thought I got rid of that issue. :-)

**Comment by johncowleyhall** [comment]
Ah shit, man. No, I think this is 1.4.1, and you're already up to 1.4.4. Well now I feel like an idiot. Sorry about that.

**Comment by andersthorborg** [comment]
Please don't. :-)
As long as it's fixed!

**Comment by johncowleyhall** [comment]
Oh, it's totally fixed. It's a great add-on, man. Very useful.

**Comment by vectrus** [comment]
Indeed a great add-on, but i still have the illegal offset error in version 1.4.10. 

PHP Warning:  Illegal string offset 'hide_cropped'     .... /wp-content/plugins/acf-image-crop-add-on/acf-image-crop-v4.php on line 895, referer: https://dev.vectrus.nl/waterschappen2017/wp-admin/post.php?post=216&action=edit


please advice
