### ISSUE TITLE
Doesn't work correctly with ACF Pro 5.2.7

### ISSUE THREAD

**Issue by monoescape** [andersthorborg/ACF-Image-Crop#28]
I'm using your plugin in a frontend form and it's been working great. Unforunately it doesn't with the latest version of ACF Pro.

The issues I'm facing:
 
1. the cropped version as well as the original size shows in the field inside the form
2. the crop button is doubled
3. when I hit one of the crop buttons an empty overlay shows up

**Comment by andersthorborg** [comment]
Hi there,
Thanks for the feedback. There's a new version in the Wordpress plugin repo that should address the issue with the latest ACF Pro release.

Also please note that this git repo is very much outdated. :-)

Best,

Anders

**Comment by monoescape** [comment]
Oh, I didn't know about this being outdated. Thanks for letting me know! :)

I already tried the latest version, but the outcome is the same.

Best,
Heiko

**Comment by monoescape** [comment]
Hi there,

I just wanted to let you know, that it’s working with the latest versions now.

It seems, I only had to refresh the page after clicking the cropbutton and so far it never happened again.

Awesome work! Thanks a lot.

Heiko
