### ISSUE TITLE
Overlay modal not appearing correctly after WordPress 4.2.2 upgrade.

### ISSUE THREAD

**Issue by seanbunton** [andersthorborg/ACF-Image-Crop#29]
It seems since upgrading to the latest WordPress (4.22) and latest version of ACF the cropper appears inline rather that in an overlay modal. The dark overlay sits over the top of everything, so the tool becomes useless and inaccessible.

I think this requires an urgent fix?

<img width="488" alt="screen shot 2015-07-14 at 12 27 18 am" src="https://cloud.githubusercontent.com/assets/851117/8651938/2850713c-29bf-11e5-8777-91a071fb4da2.png">

**Comment by grassrootshost** [comment]
I have had a similar problem, but only with certain themes.
