### ISSUE TITLE
Add image quality option

### ISSUE THREAD

**Issue by micbra** [andersthorborg/ACF-Image-Crop#41]
In the current version of the plugin a quality value of 100 is used when the crop is applied.
`$image->set_quality( apply_filters('acf-image-crop/image-quality', 100) );`

This unnecessarily blows up the filesize of the generated images and should by default better be set to 90%.

I'd even more appreciate a hook into the plugin to set the compression quality from my **functions.php** or have an option in the WP-admin's plugin settings.

**Comment by andersthorborg** [comment]
Hi there,

Actually that's exactly what the line you're referring to is doing. You can use the 'acf-image-crop/image-quality'-filter to define your own compression quality from functions.php.

**Comment by micbra** [comment]
Hey @andersthorborg , thanks for your reply.

Additionally to the general quality filter is there a possibility to set different compression/quality values for the retina and non-retina crops?
e.g I want to crop retina images with 35% and non-retina with 80% quality
