### ISSUE TITLE
Error in crop area position.

### ISSUE THREAD

**Issue by 3runoDesign** [andersthorborg/ACF-Image-Crop#64]
The crop is successfully done, but visually the crop breaks.
![screen shot 2018-05-05 at 10 30 42](https://user-images.githubusercontent.com/1563041/39663904-9481595a-5051-11e8-952d-31ed7f4fae7d.png)

**Comment by 3runoDesign** [comment]
conflict with plugins

**Comment by erik91** [comment]
@3runoDesign what was the problem?
